### ISSUE TITLE
Remove reference to an internal MoJ api?

### ISSUE THREAD

**Issue by ushkarev** [alphagov/api-catalogue#185]
There's a reference to an api used only internally by Ministry of Justice→HMPPS→Prisoner Money. I suspect it should not be listed in this api catalogue as it serves no open data and is not publicly accessible.

https://github.com/alphagov/api-catalogue/blob/91e2ebf0b9ae7b64bfd97964b75c50d06037c0f4/data/catalogue.csv#L181
references https://github.com/ministryofjustice/money-to-prisoners-api

**Comment by charlesbaird-dsa** [comment]
Hi - thanks for flagging this; the Catalogue isn't only for open or publicly accessible data, but for any government APIs - it's used as an internal resource by departments for discovery of internal APIs in the absence of an organisational catalogue. Usually best to flag the internal nature or licensing restrictions rather than remove it, but if the responsible team is keen to take it off we'll obviously oblige.
