### ISSUE TITLE
Re: 'GOV.UK Organisations'

### ISSUE THREAD

**Issue by psd** [alphagov/api-catalogue#191]
Problem with 'GOV.UK Organisations' (https://www.api.gov.uk/gds/gov-uk-organisations/)

The documentation is quite sparse, and I'm not having much luck guessing the URLs, eg I guessed `page_size` might be a valid parameter for the query string, but that doesn't seem to work.

Is it possible to download the whole dataset in a single request, or do I need to make 57 paged requests?

Also, I can see the code mentions support for CSV, but I couldn't work out what the URL might be?

**Comment by sihugh** [comment]
Hi @psd - the organisations API is quite limited. It'll only [return results in json](https://github.com/alphagov/collections/blob/d8d29033a957b33163b9b118462a6f92ca5e1f8b/app/controllers/organisations_api_controller.rb#L8) and it's fixed to [20 results per page](https://github.com/alphagov/collections/blob/d8d29033a957b33163b9b118462a6f92ca5e1f8b/app/controllers/organisations_api_controller.rb#L28), so you will need to page through. It hasn't been worked on for a while (the last time was an inter-app migration that tried to keep a faithful representation of the original implementation rather than actual feature work).

Do you have specific needs here? Our only known other non-GOV.UK consumer was the Organisations Register - which you presumably were aware of!

The information presented here comes from search API which has considerably more flexibility, so I can help with navigating you through that, if you like - though it's a little less guaranteed to be a stable API.

**Comment by jamietanna** [comment]
Hey folks - just going to close this issue as it's a conversation that hopefully we're having off this issue tracker :+1:
