### ISSUE TITLE
[West Midlands Combined Authority:Transport for West Midlands API]

### ISSUE THREAD

**Issue by keelanfh** [alphagov/api-catalogue#99]
**Base URL:**
http://api.tfwm.org.uk/

**Name:**
Transport for West Midlands API

**Description:**
The Transport for West Midlands API provides information about bus and tram services in the West Midlands. This includes station locations, timetables, routes and real-time predicted departures.

**Documentation URL:**
https://api-portal.tfwm.org.uk/docs#/

**Provider:**
West Midlands Combined Authority

**Area Served:**
West Midlands

**Alternate Name:**
WMCA

**Provider URL:**
https://www.wmca.org.uk/

**Comment by charlesbaird-dsa** [comment]
Hi - @keelanfh , thanks for adding the Transport for West Midlands API to the catalogue, it will be published in the next day or so. Is there a contact email for the maintainer of the API (a team address, rather than an individual)? Ideally we'd like to include one for each API, as our user research suggests it's one of the key pieces of information. Let me know and I'll update the record.
